package pojos;
// Generated 15-mar-2018 20:38:17 by Hibernate Tools 4.3.1



/**
 * InventarioUsuario generated by hbm2java
 */
public class InventarioUsuario  implements java.io.Serializable {


     private Integer id;
     private Inventario inventario;
     private Usuario usuario;
     private int lvl;

    public InventarioUsuario() {
    }

    public InventarioUsuario(Inventario inventario, Usuario usuario, int lvl) {
       this.inventario = inventario;
       this.usuario = usuario;
       this.lvl = lvl;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Inventario getInventario() {
        return this.inventario;
    }
    
    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getLvl() {
        return this.lvl;
    }
    
    public void setLvl(int lvl) {
        this.lvl = lvl;
    }




}


