package pojos;
// Generated 15-mar-2018 20:38:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Inventario generated by hbm2java
 */
public class Inventario  implements java.io.Serializable {


     private Integer id;
     private String oro;
     private String arma;
     private int runas;
     private int pociones;
     private Set inventarioUsuarios = new HashSet(0);

    public Inventario() {
    }

	
    public Inventario(String oro, String arma, int runas, int pociones) {
        this.oro = oro;
        this.arma = arma;
        this.runas = runas;
        this.pociones = pociones;
    }
    public Inventario(String oro, String arma, int runas, int pociones, Set inventarioUsuarios) {
       this.oro = oro;
       this.arma = arma;
       this.runas = runas;
       this.pociones = pociones;
       this.inventarioUsuarios = inventarioUsuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getOro() {
        return this.oro;
    }
    
    public void setOro(String oro) {
        this.oro = oro;
    }
    public String getArma() {
        return this.arma;
    }
    
    public void setArma(String arma) {
        this.arma = arma;
    }
    public int getRunas() {
        return this.runas;
    }
    
    public void setRunas(int runas) {
        this.runas = runas;
    }
    public int getPociones() {
        return this.pociones;
    }
    
    public void setPociones(int pociones) {
        this.pociones = pociones;
    }
    public Set getInventarioUsuarios() {
        return this.inventarioUsuarios;
    }
    
    public void setInventarioUsuarios(Set inventarioUsuarios) {
        this.inventarioUsuarios = inventarioUsuarios;
    }




}


