package pojos;
// Generated 15-mar-2018 20:38:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Nombre generated by hbm2java
 */
public class Nombre  implements java.io.Serializable {


     private Integer id;
     private String nombres;
     private String apellidop;
     private String apellidom;
     private Set usuarios = new HashSet(0);

    public Nombre() {
    }

	
    public Nombre(String nombres, String apellidop, String apellidom) {
        this.nombres = nombres;
        this.apellidop = apellidop;
        this.apellidom = apellidom;
    }
    public Nombre(String nombres, String apellidop, String apellidom, Set usuarios) {
       this.nombres = nombres;
       this.apellidop = apellidop;
       this.apellidom = apellidom;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidop() {
        return this.apellidop;
    }
    
    public void setApellidop(String apellidop) {
        this.apellidop = apellidop;
    }
    public String getApellidom() {
        return this.apellidom;
    }
    
    public void setApellidom(String apellidom) {
        this.apellidom = apellidom;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


